# Generated by Django 5.0.7 on 2025-02-16 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test_paper_subject1',
            fields=[
                ('q_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ques', models.CharField(max_length=100)),
                ('a', models.CharField(max_length=50)),
                ('b', models.CharField(max_length=50)),
                ('c', models.CharField(max_length=50)),
                ('d', models.CharField(max_length=50)),
                ('ans', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Test_paper_subject2',
            fields=[
                ('q_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ques', models.CharField(max_length=100)),
                ('a', models.CharField(max_length=50)),
                ('b', models.CharField(max_length=50)),
                ('c', models.CharField(max_length=50)),
                ('d', models.CharField(max_length=50)),
                ('ans', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Test_paper_subject3',
            fields=[
                ('q_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ques', models.CharField(max_length=100)),
                ('a', models.CharField(max_length=50)),
                ('b', models.CharField(max_length=50)),
                ('c', models.CharField(max_length=50)),
                ('d', models.CharField(max_length=50)),
                ('ans', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Test_history',
            fields=[
                ('test_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('subject', models.CharField(default='', max_length=25)),
                ('total', models.IntegerField()),
                ('correct', models.IntegerField()),
                ('wrong', models.IntegerField()),
                ('percentage', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_test.user')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(default='Unknown', max_length=255)),
                ('mother_name', models.CharField(default='Unknown', max_length=255)),
                ('phone', models.CharField(default='0000000000', max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('username', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='online_test.user')),
            ],
        ),
    ]
